import os
from typing import List, Optional, Dict, Any
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from bson import ObjectId

from database import db, create_document, get_documents

app = FastAPI(title="LexCraft AI Backend", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# -----------------------------
# Utility
# -----------------------------
class ObjectIdStr(str):
    @classmethod
    def __get_validators__(cls):
        yield cls.validate

    @classmethod
    def validate(cls, v):
        if isinstance(v, ObjectId):
            return str(v)
        try:
            _ = ObjectId(str(v))
            return str(v)
        except Exception:
            raise ValueError("Invalid ObjectId")


# -----------------------------
# Schemas
# -----------------------------
class Party(BaseModel):
    role: Optional[str] = Field(None, description="Role of the party (e.g., Landlord, Tenant)")
    name: str
    address: Optional[str] = None

class KeyTerms(BaseModel):
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    price: Optional[str] = None
    frequency: Optional[str] = None
    security_deposit: Optional[str] = None

class GenerateRequest(BaseModel):
    country: str = Field(..., pattern=r"^(Canada|U\.S\.)$")
    region: str
    contract_type: str
    parties: List[Party]
    key_terms: KeyTerms = Field(default_factory=KeyTerms)
    clauses: List[str] = Field(default_factory=list)
    title: Optional[str] = None

class ContractOut(BaseModel):
    id: ObjectIdStr
    country: str
    region: str
    contract_type: str
    parties: List[Party]
    key_terms: Dict[str, Any]
    clauses: List[str]
    html: str
    notes: Optional[str] = None


# -----------------------------
# Basic routes
# -----------------------------
@app.get("/")
def read_root():
    return {"message": "LexCraft AI Backend Running"}

@app.get("/api/hello")
def hello():
    return {"message": "Hello from LexCraft AI backend!"}


@app.get("/test")
def test_database():
    response = {
        "backend": "✅ Running",
        "database": "❌ Not Available",
        "database_url": None,
        "database_name": None,
        "connection_status": "Not Connected",
        "collections": []
    }
    try:
        if db is not None:
            response["database"] = "✅ Available"
            response["database_url"] = "✅ Set" if os.getenv("DATABASE_URL") else "❌ Not Set"
            response["database_name"] = db.name if hasattr(db, 'name') else "Unknown"
            try:
                collections = db.list_collection_names()
                response["collections"] = collections[:10]
                response["database"] = "✅ Connected & Working"
                response["connection_status"] = "Connected"
            except Exception as e:
                response["database"] = f"⚠️ Connected but Error: {str(e)[:80]}"
        else:
            response["database"] = "⚠️ Available but not initialized"
    except Exception as e:
        response["database"] = f"❌ Error: {str(e)[:80]}"
    return response


# -----------------------------
# Contract generation (MVP)
# -----------------------------

def _disclaimer(country: str) -> str:
    return (
        "This document is generated by AI for informational purposes and does not constitute legal advice. "
        "Please review with a qualified lawyer licensed in your jurisdiction before use."
    )


def _notes_ontario_residential_lease() -> str:
    return (
        "Key Ontario references: Residential Tenancies Act, 2006, S.O. 2006, c. 17; O. Reg. 516/06. "
        "Consult CanLII for up-to-date statutes and regulations."
    )


def build_contract_html(payload: GenerateRequest) -> str:
    title = payload.title or f"{payload.region} {payload.contract_type}"

    parties_block = "".join([
        f"<div><strong>{p.role or 'Party'}</strong>: {p.name}" + (f", {p.address}" if p.address else "") + "</div>"
        for p in payload.parties
    ])

    kt = payload.key_terms.model_dump() if isinstance(payload.key_terms, KeyTerms) else payload.key_terms

    key_terms = "".join([
        f"<div><strong>{k.replace('_',' ').title()}:</strong> {v}</div>" for k, v in kt.items() if v
    ])

    clauses_html = "".join([f"<li>{c}</li>" for c in payload.clauses]) or "<li>No additional clauses specified.</li>"

    notes = ""
    if payload.country == "Canada" and payload.region.lower() == "ontario" and "lease" in payload.contract_type.lower():
        notes = _notes_ontario_residential_lease()

    disclaimer = _disclaimer(payload.country)

    html = f"""
    <article style='font-family: Inter, Arial, sans-serif; max-width: 800px; margin: 0 auto; color: #111;'>
      <header style='text-align:center; margin-bottom: 24px;'>
        <h1 style='font-size: 28px; margin: 0 0 6px 0;'>{title}</h1>
        <div style='font-size: 13px; color: #555;'>Jurisdiction: {payload.country} – {payload.region}</div>
      </header>
      <section style='padding:16px; border:1px solid #eee; border-radius: 8px; background:#fff;'>
        <h2 style='font-size:16px; margin:0 0 8px 0;'>Parties</h2>
        {parties_block}
      </section>
      <section style='padding:16px; border:1px solid #eee; border-radius: 8px; background:#fff; margin-top:12px;'>
        <h2 style='font-size:16px; margin:0 0 8px 0;'>Key Terms</h2>
        {key_terms}
      </section>
      <section style='padding:16px; border:1px solid #eee; border-radius: 8px; background:#fff; margin-top:12px;'>
        <h2 style='font-size:16px; margin:0 0 8px 0;'>Clauses</h2>
        <ol style='padding-left: 18px;'>
          {clauses_html}
        </ol>
      </section>
      <aside style='display:flex; gap:12px; margin-top:16px;'>
        <div style='flex:2; font-size:12px; color:#444; background:#fafafa; border:1px dashed #ddd; padding:12px; border-radius:8px;'>
          <strong>Disclaimer:</strong> {disclaimer}
        </div>
        <div style='flex:1; font-size:12px; color:#222; background:#fff5f5; border:1px solid #ffd1d1; padding:12px; border-radius:8px;'>
          <strong>Legal Notes:</strong> {notes or 'Add relevant citations based on jurisdiction.'}
        </div>
      </aside>
    </article>
    """
    return html


@app.post("/api/contracts/generate", response_model=ContractOut)
def generate_contract(payload: GenerateRequest):
    if db is None:
        raise HTTPException(status_code=500, detail="Database not available")

    html = build_contract_html(payload)
    notes = None
    if payload.country == "Canada" and payload.region.lower() == "ontario" and "lease" in payload.contract_type.lower():
        notes = _notes_ontario_residential_lease()

    doc = {
        "country": payload.country,
        "region": payload.region,
        "contract_type": payload.contract_type,
        "parties": [p.model_dump() for p in payload.parties],
        "key_terms": payload.key_terms.model_dump() if isinstance(payload.key_terms, KeyTerms) else payload.key_terms,
        "clauses": payload.clauses,
        "html": html,
        "notes": notes,
    }

    inserted_id = create_document("contract", doc)
    saved = db["contract"].find_one({"_id": ObjectId(inserted_id)})
    return ContractOut(
        id=str(saved["_id"]),
        country=saved["country"],
        region=saved["region"],
        contract_type=saved["contract_type"],
        parties=[Party(**p) for p in saved.get("parties", [])],
        key_terms=saved.get("key_terms", {}),
        clauses=saved.get("clauses", []),
        html=saved.get("html", ""),
        notes=saved.get("notes"),
    )


class ListResponse(BaseModel):
    items: List[ContractOut]

@app.get("/api/contracts", response_model=ListResponse)
def list_contracts(limit: int = 20):
    if db is None:
        raise HTTPException(status_code=500, detail="Database not available")
    docs = get_documents("contract", limit=limit)
    items: List[ContractOut] = []
    for d in docs:
        items.append(ContractOut(
            id=str(d.get("_id")),
            country=d.get("country"),
            region=d.get("region"),
            contract_type=d.get("contract_type"),
            parties=[Party(**p) for p in d.get("parties", [])],
            key_terms=d.get("key_terms", {}),
            clauses=d.get("clauses", []),
            html=d.get("html", ""),
            notes=d.get("notes"),
        ))
    return {"items": items}


@app.get("/api/contracts/{contract_id}", response_model=ContractOut)
def get_contract(contract_id: str):
    if db is None:
        raise HTTPException(status_code=500, detail="Database not available")
    try:
        obj_id = ObjectId(contract_id)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid contract id")
    doc = db["contract"].find_one({"_id": obj_id})
    if not doc:
        raise HTTPException(status_code=404, detail="Not found")
    return ContractOut(
        id=str(doc["_id"]),
        country=doc["country"],
        region=doc["region"],
        contract_type=doc["contract_type"],
        parties=[Party(**p) for p in doc.get("parties", [])],
        key_terms=doc.get("key_terms", {}),
        clauses=doc.get("clauses", []),
        html=doc.get("html", ""),
        notes=doc.get("notes"),
    )


# -----------------------------
# Export endpoints (MVP)
# -----------------------------
from fastapi.responses import StreamingResponse
from io import BytesIO

try:
    from docx import Document
    DOCX_AVAILABLE = True
except Exception:
    DOCX_AVAILABLE = False

try:
    from reportlab.lib.pagesizes import LETTER
    from reportlab.pdfgen import canvas
    from reportlab.lib.units import inch
    PDF_AVAILABLE = True
except Exception:
    PDF_AVAILABLE = False


def _html_to_text(html: str) -> List[str]:
    # very simple conversion: strip tags, split into lines
    import re
    text = re.sub(r"<br\s*/?>", "\n", html, flags=re.I)
    text = re.sub(r"<[^>]+>", "", text)
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    return lines or ["Contract"]


@app.get("/api/contracts/{contract_id}/download.docx")
def download_docx(contract_id: str):
    if not DOCX_AVAILABLE:
        raise HTTPException(status_code=503, detail="DOCX export not available on server")
    try:
        obj_id = ObjectId(contract_id)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid contract id")
    doc = db["contract"].find_one({"_id": obj_id})
    if not doc:
        raise HTTPException(status_code=404, detail="Not found")

    document = Document()
    document.add_heading(f"{doc.get('region')} {doc.get('contract_type')}", level=1)
    for line in _html_to_text(doc.get("html", "")):
        document.add_paragraph(line)

    buf = BytesIO()
    document.save(buf)
    buf.seek(0)
    return StreamingResponse(buf, media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document", headers={
        "Content-Disposition": f"attachment; filename=contract-{contract_id}.docx"
    })


@app.get("/api/contracts/{contract_id}/download.pdf")
def download_pdf(contract_id: str):
    if not PDF_AVAILABLE:
        raise HTTPException(status_code=503, detail="PDF export not available on server")
    try:
        obj_id = ObjectId(contract_id)
    except Exception:
        raise HTTPException(status_code=400, detail="Invalid contract id")
    doc = db["contract"].find_one({"_id": obj_id})
    if not doc:
        raise HTTPException(status_code=404, detail="Not found")

    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    width, height = LETTER
    x_margin = 1 * inch
    y = height - 1 * inch

    title = f"{doc.get('region')} {doc.get('contract_type')}"
    c.setFont("Helvetica-Bold", 14)
    c.drawString(x_margin, y, title)
    y -= 0.3 * inch

    c.setFont("Helvetica", 10)
    for line in _html_to_text(doc.get("html", "")):
        if y < 1 * inch:
            c.showPage()
            y = height - 1 * inch
            c.setFont("Helvetica", 10)
        c.drawString(x_margin, y, line[:110])
        y -= 0.2 * inch

    c.showPage()
    c.save()
    buf.seek(0)
    return StreamingResponse(buf, media_type="application/pdf", headers={
        "Content-Disposition": f"attachment; filename=contract-{contract_id}.pdf"
    })


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)
